name: Deploy Prisma Migrations

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  migrate:
    name: Prisma migrate deploy (Neon)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (no scripts)
        run: npm ci --ignore-scripts

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run migrations against production database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
